-- AlterEnum
ALTER TYPE "JournalSourceType" ADD VALUE 'PLATFORM_FUND_TRANSFER';
ALTER TYPE "JournalSourceType" ADD VALUE 'PLATFORM_FUND_TRANSFER_REVERSAL';

-- AlterEnum
ALTER TYPE "PlatformJournalSourceType" ADD VALUE 'MERCHANT_FUND_TRANSFER';
ALTER TYPE "PlatformJournalSourceType" ADD VALUE 'MERCHANT_FUND_TRANSFER_REVERSAL';

-- AlterEnum
ALTER TYPE "SalesLedgerEntryType" ADD VALUE 'PLATFORM_FUND_TRANSFER';
