import { PlanCode } from "@prisma/client";

/**
 * Slugs match PermissionKey / UI keys so the frontend can map entitlements to canAccess without a second naming layer.
 */
export const PLAN_ENTITLEMENT_SLUGS: Record<PlanCode, string[]> = {
  [PlanCode.BASIC]: [
    "subscriptions.billings",
    "subscriptions.invoices",
    "subscriptions.billing_activity",
    "dashboard.view",
    "pos.access",
    "products.view",
    "products.create",
    "products.edit",
    "orders.view",
    "orders.manage",
    "payments.view",
    "payments.manage",
    "staff.manage",
    "status.change.view",
    "organization.manage",
    "business.manage",
    "business.configuration",
    "merchant.api",
    "contacts.manage",
  ],
  [PlanCode.PRO]: [
    "subscriptions.billings",
    "subscriptions.invoices",
    "subscriptions.billing_activity",
    "dashboard.view",
    "pos.access",
    "products.view",
    "products.create",
    "products.edit",
    "orders.view",
    "orders.manage",
    "payments.view",
    "payments.manage",
    "payments.export",
    "sales.quotation",
    "sales.invoice",
    "reports.view",
    "accounting.view",
    "accounting.reports.gl",
    "accounting.reports.pnl",
    "accounting.reports.statement",
    "accounting.reports.export",
    "staff.manage",
    "status.change.view",
    "organization.manage",
    "business.manage",
    "business.configuration",
    "merchant.api",
    "contacts.manage",
  ],
  [PlanCode.BUSINESS_PRO]: [
    "subscriptions.billings",
    "subscriptions.invoices",
    "subscriptions.billing_activity",
    "dashboard.view",
    "pos.access",
    "products.view",
    "products.create",
    "products.edit",
    "products.delete",
    "products.manage",
    "orders.view",
    "orders.manage",
    "payments.view",
    "payments.manage",
    "payments.export",
    "sales.quotation",
    "sales.invoice",
    "reports.view",
    "reports.export",
    "accounting.view",
    "accounting.chart.view",
    "accounting.reports.gl",
    "accounting.reports.pnl",
    "accounting.reports.statement",
    "accounting.reports.export",
    "staff.manage",
    "status.change.view",
    "organization.manage",
    "business.manage",
    "business.configuration",
    "merchant.api",
    "contacts.manage",
  ],
};

export const SYSTEM_CATALOG_SERVICES: Array<{
  id: string;
  name: string;
  description: string;
  sortOrder: number;
}> = [
  { id: "svc_core", name: "Core", description: "Dashboard and POS", sortOrder: 0 },
  { id: "svc_catalog", name: "Catalog", description: "Product catalogue", sortOrder: 1 },
  { id: "svc_sales", name: "Sales", description: "Orders and payments", sortOrder: 2 },
  { id: "svc_insights", name: "Insights", description: "Reporting", sortOrder: 3 },
  { id: "svc_finance", name: "Finance", description: "Accounting", sortOrder: 4 },
  { id: "svc_org", name: "Organization", description: "Staff and organization", sortOrder: 5 },
  {
    id: "svc_subscriptions",
    name: "Subscriptions",
    description: "Plan billing and payment methods",
    sortOrder: 6,
  },
  {
    id: "svc_merchant",
    name: "Merchant",
    description: "External wallets and APIs for customer payments",
    sortOrder: 7,
  },
];

export const SYSTEM_CATALOG_PRODUCTS: Array<{
  id: string;
  serviceId: string;
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
  navPath?: string | null;
  navLabel?: string | null;
}> = [
  {
    id: "sp_dashboard",
    serviceId: "svc_core",
    slug: "dashboard.view",
    name: "Dashboard",
    description: "Business dashboard",
    sortOrder: 0,
    navPath: "/dashboard",
    navLabel: "Dashboard",
  },
  {
    id: "sp_pos",
    serviceId: "svc_core",
    slug: "pos.access",
    name: "POS",
    description: "Point of sale",
    sortOrder: 1,
    navPath: "/pos",
    navLabel: "POS / Checkout",
  },
  {
    id: "sp_pv",
    serviceId: "svc_catalog",
    slug: "products.view",
    name: "View products",
    description: "View catalogue",
    sortOrder: 0,
    navPath: "/products",
    navLabel: "Products",
  },
  {
    id: "sp_pc",
    serviceId: "svc_catalog",
    slug: "products.create",
    name: "Create products",
    description: "Add products",
    sortOrder: 1,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_pe",
    serviceId: "svc_catalog",
    slug: "products.edit",
    name: "Edit products",
    description: "Update products",
    sortOrder: 2,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_pd",
    serviceId: "svc_catalog",
    slug: "products.delete",
    name: "Delete products",
    description: "Remove products",
    sortOrder: 3,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_pmgmt",
    serviceId: "svc_catalog",
    slug: "products.manage",
    name: "Products (full access)",
    description: "Umbrella for full catalogue control including delete",
    sortOrder: 4,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_ov",
    serviceId: "svc_sales",
    slug: "orders.view",
    name: "Orders",
    description: "View orders",
    sortOrder: 0,
    navPath: "/orders",
    navLabel: "Orders",
  },
  {
    id: "sp_omgmt",
    serviceId: "svc_sales",
    slug: "orders.manage",
    name: "Manage orders",
    description: "Create and update orders and transaction status",
    sortOrder: 1,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_payv",
    serviceId: "svc_sales",
    slug: "payments.view",
    name: "Payments",
    description: "View payments",
    sortOrder: 2,
    navPath: "/payments",
    navLabel: "Payments",
  },
  {
    id: "sp_paymgmt",
    serviceId: "svc_sales",
    slug: "payments.manage",
    name: "Manage payments",
    description: "Record, reconcile, or adjust payment records",
    sortOrder: 3,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_paye",
    serviceId: "svc_sales",
    slug: "payments.export",
    name: "Export payments",
    description: "Export payment data",
    sortOrder: 4,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_sales_quotation",
    serviceId: "svc_sales",
    slug: "sales.quotation",
    name: "Quotations",
    description: "Customer quotes; accept to create a draft invoice",
    sortOrder: 5,
    navPath: "/sales/quotations",
    navLabel: "Quotations",
  },
  {
    id: "sp_sales_invoice",
    serviceId: "svc_sales",
    slug: "sales.invoice",
    name: "Sales invoices",
    description: "Issue invoices; ledger posts when marked paid",
    sortOrder: 6,
    navPath: "/sales/invoices",
    navLabel: "Sales invoices",
  },
  {
    id: "sp_rv",
    serviceId: "svc_insights",
    slug: "reports.view",
    name: "Reports",
    description: "View reports",
    sortOrder: 0,
    navPath: "/reports",
    navLabel: "Reports",
  },
  {
    id: "sp_re",
    serviceId: "svc_insights",
    slug: "reports.export",
    name: "Export reports",
    description: "Export reports",
    sortOrder: 1,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_av",
    serviceId: "svc_finance",
    slug: "accounting.view",
    name: "Accounting",
    description: "Accounting area",
    sortOrder: 0,
    navPath: "/accounting",
    navLabel: "Accounting",
  },
  {
    id: "sp_ac",
    serviceId: "svc_finance",
    slug: "accounting.chart.view",
    name: "Chart of accounts",
    description: "View chart of accounts",
    sortOrder: 1,
    navPath: "/accounting/chart-of-accounts",
    navLabel: "Chart of accounts",
  },
  {
    id: "sp_argl",
    serviceId: "svc_finance",
    slug: "accounting.reports.gl",
    name: "GL balance report",
    description: "Trial balance / GL balances as at a date",
    sortOrder: 2,
    navPath: "/accounting/reports/gl-balance",
    navLabel: "GL balance",
  },
  {
    id: "sp_arpnl",
    serviceId: "svc_finance",
    slug: "accounting.reports.pnl",
    name: "Profit & loss report",
    description: "Income and expenses for a date range",
    sortOrder: 3,
    navPath: "/accounting/reports/profit-loss",
    navLabel: "Profit & loss",
  },
  {
    id: "sp_arstmt",
    serviceId: "svc_finance",
    slug: "accounting.reports.statement",
    name: "Account statement",
    description: "Activity for a single general ledger account",
    sortOrder: 4,
    navPath: "/accounting/reports/account-statement",
    navLabel: "Account statement",
  },
  {
    id: "sp_arexp",
    serviceId: "svc_finance",
    slug: "accounting.reports.export",
    name: "Export finance reports",
    description: "Download finance reports as PDF or CSV",
    sortOrder: 5,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_sm",
    serviceId: "svc_org",
    slug: "staff.manage",
    name: "Staff management",
    description: "Manage staff",
    sortOrder: 0,
    navPath: "/staff",
    navLabel: "Staff",
  },
  {
    id: "sp_om",
    serviceId: "svc_org",
    slug: "organization.manage",
    name: "Organization",
    description: "Manage organization",
    sortOrder: 1,
    navPath: "/businesses",
    navLabel: "My businesses",
  },
  {
    id: "sp_bizmgmt",
    serviceId: "svc_org",
    slug: "business.manage",
    name: "Business administration",
    description: "Manage business-wide operational settings",
    sortOrder: 2,
    navPath: null,
    navLabel: null,
  },
  {
    id: "sp_bcfg",
    serviceId: "svc_org",
    slug: "business.configuration",
    name: "Access configuration",
    description: "Assign plan features to team members",
    sortOrder: 3,
    navPath: "/configuration",
    navLabel: "Configuration",
  },
  {
    id: "sp_staff_status",
    serviceId: "svc_org",
    slug: "status.change.view",
    name: "Staff access status",
    description: "View and change member access: active, blocked, suspended, or terminated",
    sortOrder: 4,
    navPath: "/staff/status",
    navLabel: "Staff access status",
  },
  {
    id: "sp_contacts",
    serviceId: "svc_org",
    slug: "contacts.manage",
    name: "Contacts",
    description: "Counterparties for journals, invoices, and quotations",
    sortOrder: 5,
    navPath: "/contacts",
    navLabel: "Contacts",
  },
  {
    id: "sp_sub_billings",
    serviceId: "svc_subscriptions",
    slug: "subscriptions.billings",
    name: "Billings",
    description: "Pay subscription invoices and manage payment methods",
    sortOrder: 0,
    navPath: "/billing",
    navLabel: "Billing",
  },
  {
    id: "sp_sub_invoices",
    serviceId: "svc_subscriptions",
    slug: "subscriptions.invoices",
    name: "Invoices",
    description: "View subscription billing history for this business",
    sortOrder: 1,
    navPath: "/subscriptions/invoices",
    navLabel: "Invoices",
  },
  {
    id: "sp_sub_billing_act",
    serviceId: "svc_subscriptions",
    slug: "subscriptions.billing_activity",
    name: "Subscription payments",
    description: "Plan payment activity for your business",
    sortOrder: 2,
    navPath: "/subscriptions/billing-activity",
    navLabel: "Subscription payments",
  },
  {
    id: "sp_merchant_api",
    serviceId: "svc_merchant",
    slug: "merchant.api",
    name: "APIs",
    description: "Connect merchant wallets (Wave, Yonna) for customer checkout",
    sortOrder: 0,
    navPath: "/integrations/merchant-api",
    navLabel: "Merchant API",
  },
];
